FROM lscr.io/linuxserver/openssh-server:latest

EXPOSE 2222

ENV PUID=1000
ENV PGID=1000
ENV TZ=Etc/UTC
#ENV PUBLIC_KEY=yourpublickey
#ENV PUBLIC_KEY_FILE=/path/to/file
#ENV PUBLIC_KEY_DIR=/path/to/directory/containing/_only_/pubkeys
#ENV PUBLIC_KEY_URL=https://github.com/username.keys
ENV SUDO_ACCESS=true
ENV PASSWORD_ACCESS=true
ENV USER_PASSWORD=MyP@ss
#ENV USER_PASSWORD_FILE=/path/to/file
ENV USER_NAME=eldius
ENV LOG_STDOUT=true
