#  Template Go (Golang) build

#  This template allows you to validate your Go (Golang) code.
#  The workflow allows running tests, build and code linting on the default branch.

image: golang:1.21

pipelines:
  default:
    - parallel:
      - step:
          name: Test
          script:
            - go test ./... -cover
      - step:
          name: Lint code
          image: golangci/golangci-lint:v1.55.0
          script:
            - golangci-lint run -v
      - step:
          name: Vulnerabiliy check
          image: golangci/golangci-lint:v1.55.0
          script:
            - go install golang.org/x/vuln/cmd/govulncheck@latest


  tags:
    v*:
      - step:
          script:
            - go install github.com/goreleaser/goreleaser@latest
            - goreleaser release

      - pipe: atlassian/bitbucket-upload-file:0.6.0
        variables:
          FILENAME: dist/mineserver-manager_*
          # BITBUCKET_USERNAME: "<string>" # Optional
          # BITBUCKET_APP_PASSWORD: "<string>" # Optional
          BITBUCKET_ACCESS_TOKEN: $BITBUCKET_ACCESS_TOKEN
          # ACCOUNT: '<string>' # Optional
          # REPOSITORY: '<string>' # Optional
          DEBUG: '<boolean>' # Optional
