name: Go

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: Setup Go Versions
        uses: actions/setup-go@v6
      - name: lint
        uses: golangci/golangci-lint-action@v9
      - name: Test
        run: go test ./... -cover
      - name: vulncheck
        uses: golang/govulncheck-action@v1
        with:
           go-package: ./...
