name: Go

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: Setup Go Versions
        uses: actions/setup-go@v6
        with:
          go-version: 1.26.2
      - name: Setup dependencies
        run: |
          go mod tidy
          curl -sSfL https://golangci-lint.run/install.sh | sh -s -- -b $(go env GOPATH)/bin
      - name: validate
        run: go tool task validate
